# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], default='dinner', max_length=9),
        ),
    ]
