# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='static/img/recipeimg'),
        ),
    ]
