# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 20:03
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161228_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=''),
        ),
    ]
