# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20161228_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], default='snacks', max_length=9),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(default='', upload_to=''),
        ),
    ]
