# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
